#!/usr/bin/env python3
"""Fail-closed finite-regulator BQG spectral-history graph gate.

This tool turns a finite Hermitian positive master operator M and a seed block V
into the derived block-Krylov/Lanczos graph generated by M itself.

If the Krylov residual closes, the accumulated cyclic subspace is invariant and
the compressed operator J = Q^dag M Q reproduces every seed-sector matrix
function exactly up to the declared numerical tolerance. In particular it
reproduces finite heat kernels and the isolated zero-sector projector.

Scientific scope:
- exact/numerical finite-regulator constraint spectral diagnostic;
- NOT a continuum rigging-map theorem;
- NOT a physical time evolution;
- NOT a spacetime spectral dimension or graviton propagator.

Input mode expects an NPZ with arrays `M` and `V`.
Without --input-npz a deterministic positive self-test is executed.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Iterable

import numpy as np
from scipy.linalg import expm

DEFAULT_ABS_TOL = 2e-11
DEFAULT_REL_TOL = 5e-10
DEFAULT_MAX_DEPTH = 64


def _herm(a: np.ndarray) -> np.ndarray:
    return (a + a.conj().T) / 2


def _norm(a: np.ndarray) -> float:
    return float(np.linalg.norm(a))


def _rank_threshold(s: np.ndarray, abs_tol: float, rel_tol: float, scale: float) -> float:
    smax = float(np.max(s)) if s.size else 0.0
    return max(abs_tol, rel_tol * max(scale, smax, 1.0))


def orthonormalize_seed(
    V: np.ndarray, *, abs_tol: float, rel_tol: float
) -> tuple[np.ndarray, np.ndarray, dict]:
    """Return Q0 and C such that V = Q0 C on the numerical seed range."""
    U, s, Vh = np.linalg.svd(V, full_matrices=False)
    thresh = _rank_threshold(s, abs_tol, rel_tol, _norm(V))
    rank = int(np.count_nonzero(s > thresh))
    if rank == 0:
        raise ValueError("seed block has zero numerical rank")
    Q0 = U[:, :rank]
    C = np.diag(s[:rank]) @ Vh[:rank, :]
    reconstruction = _norm(V - Q0 @ C) / max(_norm(V), 1e-30)
    return Q0, C, {
        "input_columns": int(V.shape[1]),
        "numerical_rank": rank,
        "singular_values": [float(x) for x in s],
        "rank_threshold": float(thresh),
        "relative_reconstruction_error": float(reconstruction),
    }


def residual_factor(
    R: np.ndarray, *, abs_tol: float, rel_tol: float, scale: float
) -> tuple[np.ndarray | None, np.ndarray | None, dict]:
    """Rank-revealing factorization R = Qnext Bnext + discarded."""
    U, s, Vh = np.linalg.svd(R, full_matrices=False)
    thresh = _rank_threshold(s, abs_tol, rel_tol, scale)
    rank = int(np.count_nonzero(s > thresh))
    if rank == 0:
        return None, None, {
            "rank": 0,
            "singular_values": [float(x) for x in s],
            "threshold": float(thresh),
            "discarded_norm": float(_norm(R)),
        }
    Qn = U[:, :rank]
    Bn = np.diag(s[:rank]) @ Vh[:rank, :]
    discarded = R - Qn @ Bn
    return Qn, Bn, {
        "rank": rank,
        "singular_values": [float(x) for x in s],
        "threshold": float(thresh),
        "discarded_norm": float(_norm(discarded)),
    }


def make_block_offsets(dims: Iterable[int]) -> list[tuple[int, int]]:
    out = []
    start = 0
    for d in dims:
        out.append((start, start + int(d)))
        start += int(d)
    return out


def block_off_tridiagonal_norm(J: np.ndarray, dims: list[int]) -> float:
    offsets = make_block_offsets(dims)
    sq = 0.0
    for i, (a, b) in enumerate(offsets):
        for j, (c, d) in enumerate(offsets):
            if abs(i - j) > 1:
                sq += _norm(J[a:b, c:d]) ** 2
    return float(np.sqrt(sq))


def grouped_spectral_measure(
    J: np.ndarray, p0: int, *, eigen_tol: float
) -> tuple[list[dict], np.ndarray, np.ndarray]:
    lam, U = np.linalg.eigh(_herm(J))
    groups: list[list[int]] = []
    for i, val in enumerate(lam):
        if not groups:
            groups.append([i])
            continue
        anchor = float(lam[groups[-1][0]])
        if abs(float(val) - anchor) <= eigen_tol * max(1.0, abs(anchor), abs(float(val))):
            groups[-1].append(i)
        else:
            groups.append([i])

    rows = []
    for idxs in groups:
        Ug = U[:, idxs]
        P0Ug = Ug[:p0, :]
        W = P0Ug @ P0Ug.conj().T
        rows.append(
            {
                "lambda": float(np.mean(lam[idxs])),
                "multiplicity_in_J": int(len(idxs)),
                "seed_trace_weight": float(np.trace(W).real),
                "seed_weight_frobenius": float(np.linalg.norm(W)),
                "seed_weight_min_eigenvalue": float(np.min(np.linalg.eigvalsh(_herm(W)))),
            }
        )
    return rows, lam, U


def functional_checks(
    M: np.ndarray,
    V: np.ndarray,
    C: np.ndarray,
    J: np.ndarray,
    p0: int,
    *,
    zero_tol: float,
    heat_sigmas: tuple[float, ...] = (0.01, 0.05, 0.2, 1.0, 5.0),
) -> dict:
    """Compare full-space and compressed seed-sector matrix functions."""
    E = np.zeros((J.shape[0], p0), dtype=complex)
    E[:p0, :] = np.eye(p0)

    moment_rows = []
    for n in range(7):
        full = V.conj().T @ np.linalg.matrix_power(M, n) @ V
        comp0 = E.conj().T @ np.linalg.matrix_power(J, n) @ E
        comp = C.conj().T @ comp0 @ C
        rel = _norm(full - comp) / max(_norm(full), 1.0)
        moment_rows.append({"n": n, "relative_error": float(rel)})

    heat_rows = []
    for sigma in heat_sigmas:
        full = V.conj().T @ expm(-sigma * M) @ V
        comp0 = E.conj().T @ expm(-sigma * J) @ E
        comp = C.conj().T @ comp0 @ C
        rel = _norm(full - comp) / max(_norm(full), 1.0)
        heat_rows.append({"sigma": float(sigma), "relative_error": float(rel)})

    em, Um = np.linalg.eigh(_herm(M))
    ej, Uj = np.linalg.eigh(_herm(J))
    zm = np.abs(em) <= zero_tol
    zj = np.abs(ej) <= zero_tol
    Pm = Um[:, zm] @ Um[:, zm].conj().T if np.any(zm) else np.zeros_like(M)
    Pj = Uj[:, zj] @ Uj[:, zj].conj().T if np.any(zj) else np.zeros_like(J)
    full_p = V.conj().T @ Pm @ V
    comp0_p = E.conj().T @ Pj @ E
    comp_p = C.conj().T @ comp0_p @ C
    proj_rel = _norm(full_p - comp_p) / max(_norm(full_p), 1.0)

    return {
        "moments_n0_to_n6": moment_rows,
        "heat_kernel": heat_rows,
        "zero_projector_relative_error": float(proj_rel),
        "full_zero_rank": int(np.count_nonzero(zm)),
        "compressed_zero_rank": int(np.count_nonzero(zj)),
        "max_moment_relative_error": float(max(r["relative_error"] for r in moment_rows)),
        "max_heat_relative_error": float(max(r["relative_error"] for r in heat_rows)),
    }


def derived_spectral_observables(
    measure: list[dict], *, sigmas=(0.01, 0.05, 0.2, 1.0, 5.0), zero_tol: float
) -> dict:
    lam = np.array([r["lambda"] for r in measure], dtype=float)
    w = np.array([r["seed_trace_weight"] for r in measure], dtype=float)
    heat_rows = []
    for sigma in sigmas:
        e = np.exp(-float(sigma) * lam)
        den = float(np.sum(w * e))
        num = float(np.sum(w * lam * e))
        ds = float(2.0 * sigma * num / den) if den > 0 else None
        heat_rows.append(
            {
                "sigma": float(sigma),
                "seed_heat_trace": den,
                "constraint_spectral_dimension": ds,
            }
        )
    pos = lam > zero_tol
    zeta = {}
    for s in (0.5, 1.0, 2.0):
        zeta[str(s)] = float(np.sum(w[pos] * lam[pos] ** (-s))) if np.any(pos) else 0.0
    return {
        "heat_history": heat_rows,
        "finite_positive_spectral_zeta": zeta,
        "zero_sector_seed_trace_weight": float(np.sum(w[np.abs(lam) <= zero_tol])),
        "scope": (
            "constraint spectral observables on a finite seed-sector only; "
            "constraint_spectral_dimension is not spacetime dimension"
        ),
    }


def run(
    M: np.ndarray,
    V: np.ndarray,
    *,
    max_depth: int = DEFAULT_MAX_DEPTH,
    abs_tol: float = DEFAULT_ABS_TOL,
    rel_tol: float = DEFAULT_REL_TOL,
    input_label: str = "external_npz",
) -> dict:
    M = np.asarray(M)
    V = np.asarray(V)
    if M.ndim != 2 or M.shape[0] != M.shape[1]:
        raise ValueError("M must be square")
    if V.ndim != 2 or V.shape[0] != M.shape[0]:
        raise ValueError("V must be a matrix with V.shape[0] == M.shape[0]")
    if max_depth < 0:
        raise ValueError("max_depth must be nonnegative")

    Mscale = max(_norm(M), 1.0)
    herm_err = _norm(M - M.conj().T) / Mscale
    Mh = _herm(M)
    eigM = np.linalg.eigvalsh(Mh)
    min_eig = float(np.min(eigM))
    psd_tol = max(abs_tol, rel_tol * max(float(np.max(np.abs(eigM))), 1.0))
    hermitian_ok = bool(herm_err <= max(abs_tol, rel_tol))
    psd_ok = bool(min_eig >= -psd_tol)
    if not hermitian_ok:
        raise ValueError(f"M is not Hermitian within tolerance: relative error={herm_err:.3e}")
    if not psd_ok:
        raise ValueError(f"M is not positive semidefinite: min eigenvalue={min_eig:.3e}")

    Q0, C, seed_info = orthonormalize_seed(V, abs_tol=abs_tol, rel_tol=rel_tol)
    blocks = [Q0]
    residual_rows = []
    closure = False

    for depth in range(max_depth + 1):
        Q = np.concatenate(blocks, axis=1)
        Qn = blocks[-1]
        Y = Mh @ Qn
        R = Y - Q @ (Q.conj().T @ Y)
        rnorm = _norm(R)
        threshold = max(abs_tol, rel_tol * Mscale * max(_norm(Qn), 1.0))
        row = {
            "depth": int(depth),
            "current_block_dimension": int(Qn.shape[1]),
            "residual_norm": float(rnorm),
            "closure_threshold": float(threshold),
        }
        if rnorm <= threshold:
            row.update({"next_rank": 0, "closed_here": True})
            residual_rows.append(row)
            closure = True
            break

        Qnext, Bnext, fmeta = residual_factor(
            R, abs_tol=abs_tol, rel_tol=rel_tol, scale=Mscale
        )
        if Qnext is None:
            row.update({"next_rank": 0, "closed_here": True, "factorization": fmeta})
            residual_rows.append(row)
            closure = True
            break

        Qnext = Qnext - Q @ (Q.conj().T @ Qnext)
        Qnext, _ = np.linalg.qr(Qnext, mode="reduced")
        Bnext = Qnext.conj().T @ R
        discarded = R - Qnext @ Bnext
        row.update(
            {
                "next_rank": int(Qnext.shape[1]),
                "closed_here": False,
                "factorization": fmeta,
                "post_reorth_factorization_error": float(_norm(discarded)),
            }
        )
        residual_rows.append(row)
        blocks.append(Qnext)

    Q = np.concatenate(blocks, axis=1)
    dims = [int(b.shape[1]) for b in blocks]
    J = _herm(Q.conj().T @ Mh @ Q)
    orth_err = _norm(Q.conj().T @ Q - np.eye(Q.shape[1]))
    offtri = block_off_tridiagonal_norm(J, dims)
    action_res = _norm(Mh @ Q - Q @ J)
    action_rel = action_res / max(_norm(Mh @ Q), 1.0)

    zero_tol = max(abs_tol, rel_tol * max(float(np.max(np.abs(eigM))), 1.0))
    measure, eigJ, _ = grouped_spectral_measure(J, dims[0], eigen_tol=max(rel_tol, 1e-12))
    weight_sum = float(sum(r["seed_trace_weight"] for r in measure))
    measure_error = abs(weight_sum - dims[0])

    fchecks = functional_checks(Mh, V, C, J, dims[0], zero_tol=zero_tol)
    sobs = derived_spectral_observables(measure, zero_tol=zero_tol)

    algebra_tol = max(2e-9, 20 * rel_tol)
    closure_checks = {
        "input_Hermitian": hermitian_ok,
        "input_positive_semidefinite": psd_ok,
        "global_Krylov_orthonormality": bool(orth_err <= algebra_tol),
        "Hermitian_block_tridiagonal_structure": bool(offtri <= algebra_tol * max(_norm(J), 1.0)),
        "spectral_measure_normalized": bool(measure_error <= algebra_tol),
        "cyclic_subspace_closed": bool(closure),
    }
    if closure:
        closure_checks.update(
            {
                "closed_action_invariant": bool(action_rel <= algebra_tol),
                "moments_exact_on_seed": bool(fchecks["max_moment_relative_error"] <= 5e-8),
                "heat_history_exact_on_seed": bool(fchecks["max_heat_relative_error"] <= 5e-8),
                "zero_projector_exact_on_seed": bool(fchecks["zero_projector_relative_error"] <= 5e-8),
            }
        )

    all_finite_math_ok = bool(all(closure_checks.values()))
    science_status = (
        "FINITE_REGULATOR_SPECTRAL_HISTORY_CLOSED"
        if closure and all_finite_math_ok
        else "FINITE_REGULATOR_SPECTRAL_HISTORY_OPEN"
    )
    if input_label == "deterministic_self_test":
        science_status = (
            "ALGEBRAIC_REFERENCE_CLOSURE_PASS"
            if closure and all_finite_math_ok
            else "ALGEBRAIC_REFERENCE_CLOSURE_FAIL"
        )

    return {
        "status": "derived block-Krylov spectral history graph",
        "passed": all_finite_math_ok,
        "science_status": science_status,
        "input_label": input_label,
        "hilbert_dimension": int(M.shape[0]),
        "seed": seed_info,
        "master_operator": {
            "relative_Hermiticity_error": float(herm_err),
            "minimum_eigenvalue": min_eig,
            "maximum_eigenvalue": float(np.max(eigM)),
            "zero_tolerance": float(zero_tol),
        },
        "krylov_graph": {
            "block_dimensions": dims,
            "total_cyclic_dimension": int(Q.shape[1]),
            "closed": bool(closure),
            "residual_history": residual_rows,
            "global_orthonormality_error": float(orth_err),
            "off_block_tridiagonal_norm": float(offtri),
            "closed_action_relative_residual": float(action_rel),
            "J_eigenvalues": [float(x) for x in eigJ],
        },
        "matrix_valued_spectral_measure_summary": measure,
        "spectral_measure_trace_normalization_error": float(measure_error),
        "functional_calculus_checks": fchecks,
        "derived_constraint_spectral_observables": sobs,
        "checks": closure_checks,
        "physical_scope": {
            "finite_constraint_spectral_history_closed": bool(closure and all_finite_math_ok),
            "continuum_rigging_map_closed": False,
            "physical_projector_history_closed": False,
            "physical_time_identified": False,
            "physical_spacetime_dimension_derived": False,
            "physical_graviton_kernel_derived": False,
            "note": (
                "B_{r+1}=0 closes only the M-generated finite cyclic seed sector. "
                "It does not by itself close PHYSICAL_PROJECTOR_HISTORY."
            ),
        },
    }


def deterministic_self_test(seed: int = 260906) -> tuple[np.ndarray, np.ndarray]:
    rng = np.random.default_rng(seed)
    p = 2
    ncyc = 6
    n = 9

    A0 = np.array([[1.2, 0.13], [0.13, 1.6]])
    A1 = np.array([[2.1, -0.17], [-0.17, 2.5]])
    A2 = np.array([[3.0, 0.11], [0.11, 3.4]])
    B1 = np.array([[0.44, 0.08], [-0.06, 0.31]])
    B2 = np.array([[0.37, -0.05], [0.09, 0.28]])
    J0 = np.block(
        [
            [A0, B1.conj().T, np.zeros((p, p))],
            [B1, A1, B2.conj().T],
            [np.zeros((p, p)), B2, A2],
        ]
    )
    mine = float(np.min(np.linalg.eigvalsh(J0)))
    J0 = _herm(J0 - mine * np.eye(ncyc))

    X = rng.normal(size=(n, n)) + 1j * rng.normal(size=(n, n))
    U, _ = np.linalg.qr(X)
    Uc = U[:, :ncyc]
    Uo = U[:, ncyc:]
    M = Uc @ J0 @ Uc.conj().T
    M += Uo @ np.diag([4.5, 5.2, 6.1]) @ Uo.conj().T
    M = _herm(M)

    T = np.array([[1.0, 0.25], [-0.15, 1.4]])
    V = Uc[:, :p] @ T
    return M, V


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--input-npz", type=Path, help="NPZ containing arrays M and V")
    ap.add_argument("--output", type=Path)
    ap.add_argument("--max-depth", type=int, default=DEFAULT_MAX_DEPTH)
    ap.add_argument("--abs-tol", type=float, default=DEFAULT_ABS_TOL)
    ap.add_argument("--rel-tol", type=float, default=DEFAULT_REL_TOL)
    args = ap.parse_args()

    if args.input_npz:
        data = np.load(args.input_npz)
        if "M" not in data or "V" not in data:
            raise SystemExit("input NPZ must contain arrays `M` and `V`")
        M, V = data["M"], data["V"]
        label = str(args.input_npz)
    else:
        M, V = deterministic_self_test()
        label = "deterministic_self_test"

    try:
        out = run(
            M,
            V,
            max_depth=args.max_depth,
            abs_tol=args.abs_tol,
            rel_tol=args.rel_tol,
            input_label=label,
        )
    except Exception as exc:
        out = {
            "status": "derived block-Krylov spectral history graph",
            "passed": False,
            "science_status": "INPUT_OR_NUMERICAL_FAILURE",
            "error": f"{type(exc).__name__}: {exc}",
            "physical_scope": {
                "finite_constraint_spectral_history_closed": False,
                "physical_projector_history_closed": False,
            },
        }

    text = json.dumps(out, indent=2)
    print(text)
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(text + "\n", encoding="utf-8")
    return 0 if out.get("passed") else 1


if __name__ == "__main__":
    raise SystemExit(main())
