#!/usr/bin/env python3
"""Assemble a finite graph-changing K5 constraint shell and master matrix.

This is the first direct bridge from the real regulator-safe Peter-Weyl K5
Hamiltonian implementation to graph-sector blocks of a finite master kernel.

Important scope:
- basis states are the orthonormal Peter-Weyl/intertwiner keys used by the K5 gate;
- j=0 links are removed when assigning the abstract graph signature;
- the shell is generated by repeated applications of the five node H_v operators;
- C_v is compressed to the finite shell, so convergence with shell depth/cutoff
  must be checked before any block is interpreted as a physical amplitude;
- no graph-growth probability is introduced by hand.
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

import k5_peter_weyl_safe_hda_column as K5


def graph_signature(key):
    """Abstract labelled-edge signature after cylindrical removal of j=0 links."""
    spins, _Ks = key
    active = tuple(K5.EDGES[i] for i, s2 in enumerate(spins) if s2 != 0)
    return active


def apply_H_to_key(key, v: int, jmax2: int):
    return K5.prune_state(K5.apply_H_cached_state({key: 1.0 + 0.0j}, v, jmax2), 1e-10)


def generate_shell(depth: int, jmax2: int):
    initial = K5.basis_full_jhalf()[0]
    levels = [{initial}]
    seen = {initial}
    frontier = {initial}
    for _ in range(depth):
        nxt = set()
        for key in frontier:
            for v in K5.VERT:
                nxt.update(apply_H_to_key(key, v, jmax2).keys())
        nxt -= seen
        levels.append(nxt)
        seen |= nxt
        frontier = nxt
        if not frontier:
            break
    basis = sorted(seen, key=repr)
    return initial, levels, basis


def compressed_constraints(basis, jmax2: int):
    index = {k: i for i, k in enumerate(basis)}
    mats = []
    leakage = []
    for v in K5.VERT:
        C = np.zeros((len(basis), len(basis)), dtype=complex)
        leak2 = 0.0
        kept2 = 0.0
        for j, key in enumerate(basis):
            out = apply_H_to_key(key, v, jmax2)
            for ko, amp in out.items():
                if ko in index:
                    C[index[ko], j] += amp
                    kept2 += abs(amp) ** 2
                else:
                    leak2 += abs(amp) ** 2
        mats.append(C)
        total = kept2 + leak2
        leakage.append({
            "vertex": v,
            "kept_norm2": kept2,
            "outside_shell_norm2": leak2,
            "outside_fraction": (leak2 / total if total else 0.0),
        })
    return mats, leakage


def master_matrix(constraints):
    # Canonical first control: identity positive metric in constraint-label space.
    M = np.zeros_like(constraints[0])
    for C in constraints:
        M += C.conj().T @ C
    return (M + M.conj().T) / 2


def projector_from_master(M, reltol=1e-10):
    ev, U = np.linalg.eigh(M)
    scale = max(float(np.max(np.abs(ev))), 1.0)
    zero = ev < reltol * scale
    P0 = U[:, zero] @ U[:, zero].conj().T if np.any(zero) else np.zeros_like(M)
    positive = ev[~zero]
    return ev, P0, int(np.sum(zero)), (float(np.min(positive)) if len(positive) else None)


def graph_blocks(basis, P0):
    groups = defaultdict(list)
    for i, key in enumerate(basis):
        groups[graph_signature(key)].append(i)
    sigs = list(groups)
    rows = []
    for a, ga in enumerate(sigs):
        ia = groups[ga]
        for b, gb in enumerate(sigs):
            ib = groups[gb]
            block = P0[np.ix_(ib, ia)]
            fro = float(np.linalg.norm(block))
            if fro > 1e-12:
                rows.append({
                    "source_active_edge_count": len(ga),
                    "target_active_edge_count": len(gb),
                    "source_sector_dim": len(ia),
                    "target_sector_dim": len(ib),
                    "frobenius_norm": fro,
                    "changes_graph": ga != gb,
                    "source_signature": [list(e) for e in ga],
                    "target_signature": [list(e) for e in gb],
                })
    rows.sort(key=lambda r: r["frobenius_norm"], reverse=True)
    return groups, rows


def run(depth: int = 1, jmax2: int = 5):
    initial, levels, basis = generate_shell(depth, jmax2)
    constraints, leakage = compressed_constraints(basis, jmax2)
    M = master_matrix(constraints)
    herm_err = float(np.linalg.norm(M - M.conj().T))
    min_ev = float(np.min(np.linalg.eigvalsh(M))) if len(basis) else 0.0
    ev, P0, nullity, gap = projector_from_master(M)
    groups, blocks = graph_blocks(basis, P0)

    init_sig = graph_signature(initial)
    changed_basis = sum(1 for k in basis if graph_signature(k) != init_sig)
    changed_blocks = [b for b in blocks if b["changes_graph"]]

    return {
        "status": "K5 Peter-Weyl graph-sector compressed master-shell diagnostic",
        "depth": depth,
        "Jmax": jmax2 / 2,
        "basis_dimension": len(basis),
        "level_sizes": [len(x) for x in levels],
        "graph_sector_count": len(groups),
        "basis_states_outside_initial_graph": changed_basis,
        "constraint_shell_leakage": leakage,
        "master_hermiticity_error": herm_err,
        "master_min_eigenvalue": min_ev,
        "master_zero_rank": nullity,
        "master_gap_on_compressed_shell": gap,
        "eigenvalues": [float(x) for x in ev],
        "nonzero_graph_blocks": blocks,
        "nonzero_cross_graph_block_count": len(changed_blocks),
        "passed_structural_checks": bool(
            herm_err < 1e-8
            and min_ev > -1e-8
            and len(groups) >= 1
        ),
        "scope": (
            "Real K5/Peter-Weyl H_v operators, but compressed finite shell. "
            "Physical graph-transition amplitudes require shell-depth/Jmax convergence "
            "and a stable zero-mode projector before interpretation."
        ),
    }


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--depth", type=int, default=1)
    ap.add_argument("--jmax2", type=int, default=5)
    ap.add_argument("--output", type=Path)
    args = ap.parse_args()
    out = run(args.depth, args.jmax2)
    text = json.dumps(out, indent=2)
    print(text)
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(text + "\n", encoding="utf-8")
    return 0 if out["passed_structural_checks"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
