#!/usr/bin/env python3
"""Generic Hermitian Lorentzian S adapter for the frozen BQG PL operator.

This is an engineering bridge, not a new operator.  It reuses the frozen
research/bcqg-core-candidate-v1 primitives and only removes the old hard-coded
16-cell vacuum/graph wrapper so the same operator can be applied to an
arbitrary Gauss-basis state on any four-valent PL dual graph supported by the
existing backend.

Frozen definition:
    S = -i/2 (L_raw - L_raw^dagger).

The adjoint is evaluated by the upstream explicit reversed-ordering primitive;
it is never approximated by conjugating forward amplitudes.
"""
from __future__ import annotations

import argparse
import contextlib
import importlib
import json
import math
import subprocess
import sys
from pathlib import Path
from typing import Dict, Iterable, Mapping, MutableMapping, Tuple

import numpy as np

EXPECTED_UPSTREAM_SHA = "730237536cb2a3efc818b6b11fb3ebedc60ed16b"
DEFAULT_TOL = 1e-10


def _add(dst: MutableMapping, src: Mapping, scale: complex = 1.0,
         tol: float = DEFAULT_TOL) -> None:
    for key, amp in src.items():
        z = dst.get(key, 0j) + scale * amp
        if abs(z) > tol:
            dst[key] = z
        elif key in dst:
            del dst[key]


def _norm2(state: Mapping) -> float:
    return float(sum(abs(z) ** 2 for z in state.values()))


def _max_spin(state: Mapping) -> float:
    return max((max(key[0]) for key in state), default=0) / 2.0


def _verify_upstream_checkout(root: Path, expected_sha: str) -> str:
    got = subprocess.check_output(
        ["git", "-C", str(root), "rev-parse", "HEAD"], text=True
    ).strip()
    if got != expected_sha:
        raise RuntimeError(
            f"frozen upstream SHA mismatch: expected {expected_sha}, got {got}"
        )
    return got


def _load_upstream(root: Path):
    scripts = root / "scripts"
    if not scripts.is_dir():
        raise RuntimeError(f"missing upstream scripts directory: {scripts}")
    sys.path.insert(0, str(scripts))
    modules = {
        "LP": importlib.import_module(
            "peter_weyl_lorentzian_logical_projection_gate"
        ),
        "GW": importlib.import_module("pl_lorentzian_group_worker"),
        "W": importlib.import_module("pl_lorentzian_triple_worker"),
        "PCB": importlib.import_module("pl_covariant_backend"),
        "TVB": importlib.import_module("tetrahedral_volume_backend"),
        "LGA": importlib.import_module("peter_weyl_lorentzian_gauss_action_gate"),
    }
    return modules


def _four_valent_guard(D, source: int) -> None:
    local = [D.neighbor[(source, r)] for r in range(4)]
    if len(set(local)) != 4:
        raise RuntimeError(
            f"source node {source} does not have four distinct local neighbours"
        )


def _apply_s_basis_installed(
    D,
    G,
    key,
    source: int,
    modules,
    caches,
    *,
    tol: float,
):
    """Apply full Hermitian S to one Gauss basis key inside installed contexts."""
    LP, GW, W = modules["LP"], modules["GW"], modules["W"]
    _four_valent_guard(D, source)

    out: Dict = {}
    term_meta = []
    seen = set()

    # The frozen 24 oriented triples are generated by ordered_spec.  For every
    # term use the explicit forward and explicit adjoint orderings from the
    # upstream worker.  This is exactly S=-i/2(L-L^dagger).
    for idx in range(24):
        omit, base, perm, targets, coef = W.ordered_spec(D, source, idx)
        if int(coef) not in (-1, 1):
            raise RuntimeError(("bad epsilon coefficient", idx, coef))
        signature = (int(omit), tuple(perm))
        if signature in seen:
            raise RuntimeError(("duplicate oriented triple", signature))
        seen.add(signature)

        fwd, mf = GW.evaluate(D, G, key, source, idx, "forward", caches)
        adj, ma = GW.evaluate(D, G, key, source, idx, "adjoint", caches)
        if not (mf["passed"] and ma["passed"]):
            raise RuntimeError(
                f"upstream Lorentzian primitive failed at term {idx}: "
                f"forward={mf['passed']} adjoint={ma['passed']}"
            )

        _add(out, fwd, -0.5j * int(coef), tol)
        _add(out, adj, +0.5j * int(coef), tol)
        term_meta.append(
            {
                "index": idx,
                "omitted_local_slot": int(omit),
                "permuted_local_slots": list(perm),
                "epsilon_coefficient": int(coef),
                "forward_support": len(fwd),
                "adjoint_support": len(adj),
                "forward_max_leakage": float(
                    mf["physical_acceptance_max_leakage"]
                ),
                "adjoint_max_leakage": float(
                    ma["physical_acceptance_max_leakage"]
                ),
            }
        )

    if len(seen) != 24:
        raise RuntimeError(f"expected 24 unique oriented triples, got {len(seen)}")
    return out, term_meta


def apply_s_state(
    D,
    G,
    state: Mapping,
    source: int,
    modules,
    *,
    jmax2: int,
    tol: float = DEFAULT_TOL,
):
    """Apply frozen Hermitian S linearly to an arbitrary Gauss-basis state."""
    LP, PCB, TVB = modules["LP"], modules["PCB"], modules["TVB"]
    if not state:
        return {}, {
            "passed": True,
            "input_support": 0,
            "output_support": 0,
            "output_norm": 0.0,
            "terms_per_basis_key": 48,
        }

    old_j = LP.JMAX2
    out: Dict = {}
    all_meta = []
    max_leak = 0.0

    # The charged tetrahedral volume and PL graph substitutions are precisely
    # the frozen production contexts used by the v4 direct-Hermitian worker.
    with TVB.install_tetrahedral_volume_backend():
        with PCB.install_pl_graph(G):
            LP.JMAX2 = int(jmax2)
            restore, caches = LP.install_sine_cached_stack()
            try:
                for key, amp in state.items():
                    if abs(amp) <= tol:
                        continue
                    col, meta = _apply_s_basis_installed(
                        D, G, key, source, modules, caches, tol=tol
                    )
                    _add(out, col, amp, tol)
                    all_meta.append(meta)
                    for item in meta:
                        max_leak = max(
                            max_leak,
                            item["forward_max_leakage"],
                            item["adjoint_max_leakage"],
                        )
            finally:
                restore()
                LP.JMAX2 = old_j

    finite = all(np.isfinite([z.real, z.imag]).all() for z in out.values())
    summary = {
        "status": "generic frozen Hermitian PL Lorentzian S action",
        "passed": bool(finite and max_leak < 1e-8),
        "operator_definition": "S=-i/2*(L_raw-L_raw^dagger)",
        "adjoint_definition": "explicit reversed ordering V K_b K_a",
        "input_support": len(state),
        "output_support": len(out),
        "output_norm": math.sqrt(_norm2(out)),
        "output_max_spin": _max_spin(out),
        "Jmax": jmax2 / 2.0,
        "max_primitive_physical_leakage": max_leak,
        "oriented_terms_per_basis_key": 24,
        "forward_plus_adjoint_primitives_per_basis_key": 48,
        "basis_columns_evaluated": len(all_meta),
        "scope_note": (
            "Engineering adapter only: same frozen Lorentzian primitives, "
            "same coefficients, same charged-volume backend, arbitrary "
            "supported four-valent PL graph/state."
        ),
    }
    return out, summary


def _bookkeeping_selftest() -> dict:
    """Pure algebra test: all 24 terms appear once and pair partition is exact."""
    triples = []
    for omit in range(4):
        base = tuple(r for r in range(4) if r != omit)
        cycles = (
            base,
            (base[1], base[2], base[0]),
            (base[2], base[0], base[1]),
        )
        for p in cycles:
            q = (p[1], p[0], p[2])
            triples.extend([(omit, p), (omit, q)])
    unique = set(triples)
    return {
        "passed": len(triples) == 24 and len(unique) == 24,
        "pair_contributions": 12,
        "oriented_terms": len(triples),
        "unique_oriented_terms": len(unique),
    }


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--upstream-root", type=Path, required=True)
    p.add_argument("--expected-upstream-sha", default=EXPECTED_UPSTREAM_SHA)
    p.add_argument("--selftest-only", action="store_true")
    p.add_argument("--output", type=Path)
    args = p.parse_args()

    result = {
        "adapter": "bqg_pl_hermitian_s_adapter",
        "expected_upstream_sha": args.expected_upstream_sha,
        "bookkeeping": _bookkeeping_selftest(),
    }
    try:
        got = _verify_upstream_checkout(
            args.upstream_root.resolve(), args.expected_upstream_sha
        )
        result["upstream_sha"] = got
        modules = _load_upstream(args.upstream_root.resolve())
        result["imports"] = sorted(modules)
        result["passed"] = bool(result["bookkeeping"]["passed"])
        # Heavy amplitude evaluation is deliberately not hidden inside CI
        # preflight.  Production callers import apply_s_state() and provide
        # the actual L1 state and source node.
        result["science_status"] = (
            "ADAPTER_PREFLIGHT_ONLY"
            if args.selftest_only
            else "ADAPTER_READY_FOR_EXACT_AMPLITUDE_CALL"
        )
    except Exception as exc:
        result["passed"] = False
        result["error_type"] = type(exc).__name__
        result["error"] = str(exc)

    text = json.dumps(result, indent=2, sort_keys=True) + "\n"
    print(text, end="")
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(text, encoding="utf-8")
    return 0 if result["passed"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
