#!/usr/bin/env python3
"""FLRW history effective action -> rho_hist, p_hist, w_hist.

The gate closes the deterministic minisuperspace variational consumer of a
future theory-specific BQG Gamma_FLRW.  It does not construct Gamma_FLRW.

For one comoving coordinate-volume unit and metric
  ds^2 = -N(t)^2 dt^2 + a(t)^2 dx^2,
write Gamma_hist = int dt L_Gamma(a,N,adot,Ndot).
With the frozen covariant-metric variation convention
  delta Gamma = 1/2 int sqrt(-g) T^{mu nu} delta g_{mu nu},
one has
  rho_hist = - E_N[L_Gamma]/a^3,
  p_hist   =   E_a[L_Gamma]/(3 N a^2),
where E_q is the Euler-Lagrange derivative.  The implementation supports
first-derivative minisuperspace Lagrangians and keeps second derivatives as
symbols generated by the total-time derivative.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any
import sympy as sp

a,N,adot,Ndot,addot,Nddot=sp.symbols('a N adot Ndot addot Nddot', nonzero=True)
rho0,w0=sp.symbols('rho0 w0', positive=True)
LOCALS={'a':a,'N':N,'adot':adot,'Ndot':Ndot,'addot':addot,'Nddot':Nddot,'rho0':rho0,'w0':w0}

REQUIRED_FLAGS=(
    'theory_specific_flrw_history',
    'absolute_zero_source_normalization_preserved',
    'background_variational_convention_certified',
    'same_physical_history_as_scalar_sector',
)
REQUIRED_PROVENANCE=(
    'flrw_history_hash',
    'background_convention_hash',
    'history_measure_hash',
)


def expr(x:Any)->sp.Expr:
    return sp.sympify(x,locals=LOCALS)


def Dt(f:sp.Expr)->sp.Expr:
    return sp.simplify(
        sp.diff(f,a)*adot + sp.diff(f,N)*Ndot
        + sp.diff(f,adot)*addot + sp.diff(f,Ndot)*Nddot
    )


def euler(L:sp.Expr,q:sp.Symbol,qdot:sp.Symbol)->sp.Expr:
    return sp.simplify(sp.diff(L,q)-Dt(sp.diff(L,qdot)))


def derive(packet:dict[str,Any])->dict[str,Any]:
    errors:list[str]=[]
    if packet.get('schema')!='BQG_FLRW_HISTORY_EFFECTIVE_ACTION_V1':
        errors.append('schema must be BQG_FLRW_HISTORY_EFFECTIVE_ACTION_V1')
    try:
        L=expr(packet.get('L_Gamma','0'))
    except Exception as exc:
        errors.append(f'invalid L_Gamma: {exc}'); L=sp.Integer(0)
    EN=euler(L,N,Ndot)
    Ea=euler(L,a,adot)
    rho=sp.factor(-EN/a**3)
    p=sp.factor(Ea/(3*N*a**2))
    w=sp.simplify(p/rho) if sp.simplify(rho)!=0 else sp.nan
    continuity=sp.factor(Dt(rho)+3*(adot/a)*(rho+p))
    flags=packet.get('physical_flags',{}) if isinstance(packet.get('physical_flags',{}),dict) else {}
    prov=packet.get('provenance',{}) if isinstance(packet.get('provenance',{}),dict) else {}
    missing_flags=[x for x in REQUIRED_FLAGS if flags.get(x) is not True]
    missing_prov=[x for x in REQUIRED_PROVENANCE if not prov.get(x)]
    physical=not errors and not missing_flags and not missing_prov
    return {
        'schema':'BQG_FLRW_HISTORY_STRESS_RESPONSE_V1',
        'passed':not errors,
        'science_status':'PHYSICAL_FLRW_HISTORY_STRESS_DERIVED' if physical else 'FLRW_VARIATIONAL_CONSUMER_VALID_PHYSICAL_GAMMA_INCOMPLETE',
        'physical_interpretation_allowed':physical,
        'L_Gamma':str(L),
        'Euler_N':str(EN),
        'Euler_a':str(Ea),
        'rho_hist':str(rho),
        'p_hist':str(p),
        'w_hist':str(w),
        'continuity_residual':str(continuity),
        'N_equals_1':{
            'rho_hist':str(sp.simplify(rho.subs({N:1,Ndot:0,Nddot:0}))),
            'p_hist':str(sp.simplify(p.subs({N:1,Ndot:0,Nddot:0}))),
            'w_hist':str(sp.simplify(w.subs({N:1,Ndot:0,Nddot:0}))) if w is not sp.nan else 'nan',
            'continuity_residual':str(sp.simplify(continuity.subs({N:1,Ndot:0,Nddot:0}))),
        },
        'variation_convention':'delta Gamma = 1/2 int sqrt(-g) T^{mu nu} delta g_{mu nu}; ds2=-N2dt2+a2dx2',
        'missing_required_flags':missing_flags,
        'missing_required_provenance':missing_prov,
        'claim_boundary':'This derives rho,p,w from a supplied Gamma_FLRW. It does not derive Gamma_FLRW, and normalized W(0)=0 is not an absolute vacuum-energy input.',
        'errors':errors,
    }


def selftest()->dict[str,Any]:
    tests={}
    base={'schema':'BQG_FLRW_HISTORY_EFFECTIVE_ACTION_V1','physical_flags':{},'provenance':{}}

    vac=derive({**base,'L_Gamma':'-N*a**3*rho0'})
    tests['vacuum_rho']=sp.simplify(expr(vac['rho_hist'])-rho0)==0
    tests['vacuum_p_minus_rho']=sp.simplify(expr(vac['p_hist'])+rho0)==0
    tests['vacuum_w_minus_one']=sp.simplify(expr(vac['w_hist'])+1)==0
    tests['vacuum_continuity']=sp.simplify(expr(vac['continuity_residual']))==0

    dust=derive({**base,'L_Gamma':'-N*rho0'})
    tests['dust_rho_a_minus3']=sp.simplify(expr(dust['rho_hist'])-rho0/a**3)==0
    tests['dust_pressure_zero']=sp.simplify(expr(dust['p_hist']))==0
    tests['dust_w_zero']=sp.simplify(expr(dust['w_hist']))==0
    tests['dust_continuity']=sp.simplify(expr(dust['continuity_residual']))==0

    rad=derive({**base,'L_Gamma':'-N*rho0/a'})
    tests['radiation_rho_a_minus4']=sp.simplify(expr(rad['rho_hist'])-rho0/a**4)==0
    tests['radiation_p_rho_over3']=sp.simplify(expr(rad['p_hist'])-rho0/(3*a**4))==0
    tests['radiation_w_one_third']=sp.simplify(expr(rad['w_hist'])-sp.Rational(1,3))==0
    tests['radiation_continuity']=sp.simplify(expr(rad['continuity_residual']))==0

    general=derive({**base,'L_Gamma':'-N*rho0*a**(-3*w0)'})
    # This L equals -N*a^3*rho with rho=rho0*a^-3(1+w0).
    tests['constant_w_control']=sp.simplify(expr(general['w_hist'])-w0)==0
    tests['constant_w_continuity']=sp.simplify(expr(general['continuity_residual']))==0

    # Derivative dependence checks the Euler operator rather than only partial derivatives.
    deriv=derive({**base,'L_Gamma':'adot**2/N'})
    expected_EN=-adot**2/N**2
    expected_Ea=-2*addot/N+2*adot*Ndot/N**2
    tests['Euler_N_derivative_control']=sp.simplify(expr(deriv['Euler_N'])-expected_EN)==0
    tests['Euler_a_derivative_control']=sp.simplify(expr(deriv['Euler_a'])-expected_Ea)==0

    physical={
        'schema':'BQG_FLRW_HISTORY_EFFECTIVE_ACTION_V1','L_Gamma':'-N*a**3*rho0',
        'physical_flags':{x:True for x in REQUIRED_FLAGS},
        'provenance':{x:'synthetic-control' for x in REQUIRED_PROVENANCE},
    }
    phys=derive(physical)
    tests['complete_synthetic_Gamma_allows_physical_consumer']=phys['physical_interpretation_allowed'] is True
    bad=json.loads(json.dumps(physical)); bad['physical_flags']['absolute_zero_source_normalization_preserved']=False
    tests['normalized_zero_source_shortcut_fails_closed']=derive(bad)['physical_interpretation_allowed'] is False
    return {'passed':all(tests.values()),'tests':tests,'controls':{'vacuum':vac,'dust':dust,'radiation':rad,'derivative':deriv,'physical':phys}}


def main()->int:
    ap=argparse.ArgumentParser(description=__doc__); ap.add_argument('--packet',type=Path); ap.add_argument('--output',type=Path); aargs=ap.parse_args()
    out={'selftest':selftest()}
    if aargs.packet: out['production']=derive(json.loads(aargs.packet.read_text(encoding='utf-8')))
    out['passed']=bool(out['selftest']['passed'] and (not aargs.packet or out['production']['passed']))
    txt=json.dumps(out,indent=2); print(txt)
    if aargs.output: aargs.output.parent.mkdir(parents=True,exist_ok=True); aargs.output.write_text(txt+'\n',encoding='utf-8')
    return 0 if out['passed'] else 1

if __name__=='__main__': raise SystemExit(main())
