#!/usr/bin/env python3
"""Exact 140D K5 quantum-HDA first falsifier.

Build one node Hamiltonian candidate S_v by summing the 12 already-defined
local anti-oriented Thiemann/BF-like kernels T(v;a,b|c).  The script does not
fit a diffeomorphism operator.  Instead it asks the cheaper necessary question:
what operator sector is generated by [H_v,H_w] on the 32D fully-active K5
boundary sector?

Three orderings are reported:
  raw       S_v
  herm      (S_v+S_v^dag)/2
  antiherm  (S_v-S_v^dag)/(2 i)

For each pair v<w it measures
  * leakage of the commutator out of the fixed fully-active triangulation;
  * Frobenius residual after fitting (-i)[H_v,H_w] inside the full sector to
    Pauli strings of weight <=1 and <=2 on the five tetrahedral intertwiner
    qubits.

A large out-of-sector leakage is a necessary-condition failure for interpreting
the commutator as a tangential deformation on the same K5 boundary.  A small
leakage is not by itself HDA closure; the Bonzom--Dittrich coefficient and the
actual D(k,l) generator must then be tested separately.
"""
from __future__ import annotations
import argparse,itertools,json,sys
from pathlib import Path
import numpy as np

HERE=Path(__file__).resolve().parent
if str(HERE) not in sys.path:sys.path.insert(0,str(HERE))
import k5_thiemann_constraint_gate as T

I=np.eye(2,dtype=complex)
X=np.array([[0,1],[1,0]],complex)
Y=np.array([[0,-1j],[1j,0]],complex)
Z=np.array([[1,0],[0,-1]],complex)
PAULI=[I,X,Y,Z]


def build_node_matrices():
    meta,states,reverse,Up,Ud,powers,full_order,V5,target,trans=T.build_runtime()
    local=T.make_actions(Up,Ud,powers,trans); specs=T.local_specs()
    node=[]; max_raw_projection_leak=0.0
    for v in range(5):
        M=np.zeros((140,140),complex)
        for col,raw0 in enumerate(states):
            raw={}
            for spec in (s for s in specs if s[0]==v):
                T.add_scaled(raw,local(raw0,*spec))
            rn=T.raw_norm(raw); pv=T.project_state(raw,reverse); M[:,col]=pv
            if rn>1e-12:
                max_raw_projection_leak=max(max_raw_projection_leak,max(0.0,1-(np.linalg.norm(pv)/rn)**2))
        node.append(M)
    return meta,np.asarray(full_order,int),V5,node,max_raw_projection_leak


def pauli_design(max_weight:int):
    mats=[];labels=[]
    for word in itertools.product(range(4),repeat=5):
        w=sum(x!=0 for x in word)
        if w>max_weight:continue
        M=np.array([[1]],complex)
        for a in word:M=np.kron(M,PAULI[a])
        mats.append(M);labels.append(''.join('IXYZ'[a] for a in word))
    A=np.column_stack([m.reshape(-1) for m in mats])
    return A,labels

DES1,_=pauli_design(1);DES2,_=pauli_design(2)


def fit_residual(M,design):
    c,*_=np.linalg.lstsq(design,M.reshape(-1),rcond=None)
    r=M.reshape(-1)-design@c
    return float(np.linalg.norm(r)/max(np.linalg.norm(M),1e-30))


def ordering(nodes,name):
    if name=='raw':return nodes
    if name=='herm':return [0.5*(A+A.conj().T) for A in nodes]
    if name=='antiherm':return [(A-A.conj().T)/(2j) for A in nodes]
    raise ValueError(name)


def analyse(nodes,full_order,name):
    H=ordering(nodes,name);Pcols=full_order
    rows=[]
    for v,w in itertools.combinations(range(5),2):
        C=H[v]@H[w]-H[w]@H[v]
        action=C[:,Pcols]
        total=np.linalg.norm(action)
        inside=C[np.ix_(Pcols,Pcols)]
        outside=action.copy(); outside[Pcols,:]=0
        leak=float(np.linalg.norm(outside)/max(total,1e-30))
        # For Hermitian H, -i[H,H] is Hermitian.  For diagnostics we apply the
        # same phase to every ordering before Pauli-span fitting.
        D=(-1j)*inside
        rows.append({'v':v,'w':w,'commutator_action_norm':float(total),'full_sector_leakage':leak,'weight1_Pauli_residual':fit_residual(D,DES1),'weight2_Pauli_residual':fit_residual(D,DES2)})
    return {
      'ordering':name,
      'node_hermiticity_residuals':[float(np.linalg.norm(A-A.conj().T)/max(np.linalg.norm(A),1e-30)) for A in H],
      'pairs':rows,
      'max_full_sector_leakage':max(r['full_sector_leakage'] for r in rows),
      'median_full_sector_leakage':float(np.median([r['full_sector_leakage'] for r in rows])),
      'median_weight1_Pauli_residual':float(np.median([r['weight1_Pauli_residual'] for r in rows])),
      'median_weight2_Pauli_residual':float(np.median([r['weight2_Pauli_residual'] for r in rows]))
    }


def run():
    meta,full,V5,nodes,projleak=build_node_matrices()
    out=[analyse(nodes,full,x) for x in ('raw','herm','antiherm')]
    # This is a diagnostic/falsifier: do not manufacture a PASS by choosing an
    # ordering.  A robust necessary-condition pass requires at least one
    # predeclared Hermitian completion to keep median triangulation leakage <1%.
    herm=next(x for x in out if x['ordering']=='herm')
    passed=bool(herm['median_full_sector_leakage']<1e-2)
    return {
      'status':'exact K5 quantum-HDA commutator-sector diagnostic',
      'passed_necessary_fixed_triangulation_gate_for_hermitian_completion':passed,
      'Gauss_dimension':len(meta),'fully_active_dimension':len(full),
      'max_raw_to_Gauss_projection_leakage':float(projleak),
      'orderings':out,
      'interpretation_boundary':'This does NOT test the 1/(3V) simplex-HDA coefficient. It only asks whether the HH commutator of the existing finite constraint regularization acts predominantly as an operator on the same fully-active K5 triangulation and how low-body its induced tangential/shape action is.',
      'next_if_pass':'Construct D(k,l) from boundary flux/shape generators and compare [H_k,H_l] to i[D(l,k)-D(k,l)]/(3 V_tet) on semiclassical states.',
      'next_if_fail':'Do not tune coefficients. The j=1/2 BF-like regularization is not a viable quantum-HDA realization; move to a regulator-safe Peter-Weyl Jmax>=3/2 collective sector with genuine non-scalar volume and the full Lorentzian correction.'
    }


def main():
    ap=argparse.ArgumentParser(description=__doc__);ap.add_argument('--output',type=Path);a=ap.parse_args();o=run();t=json.dumps(o,indent=2);print(t)
    if a.output:a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(t+'\n',encoding='utf-8')
    return 0
if __name__=='__main__':raise SystemExit(main())
