#!/usr/bin/env python3
"""Exact flat-background scalar ADM Ward quotient.

For the linear scalar metric variables

    x = (deltaN, B, zeta, E)

with h00=-2 deltaN, h0i=partial_i B and
hij=2 zeta delta_ij + 2 partial_i partial_j E, use a formal time-derivative
symbol D.  Under scalar linearized diffeomorphisms (T,L), in the convention
used here,

    delta(deltaN) = -D T
    delta B        =  T - D L
    delta zeta     =  0
    delta E        = -L.

The exact quotient is generated by

    Q = deltaN + D B - D^2 E,
    zeta.

Hence every symmetric quadratic kernel satisfying K G=0 is the pullback of a
2x2 kernel on (Q,zeta) and contains exactly three independent scalar functions.
This is a Ward/algebra result on a flat local background, not the full FLRW
Bardeen reduction and not a theory-specific BQG history kernel.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sympy as sp


def z(M: sp.Matrix) -> bool:
    return all(sp.simplify(x)==0 for x in M)


def run() -> dict[str, object]:
    D=sp.symbols('D', nonzero=True)
    A,B,C=sp.symbols('A B C')

    # columns = time scalar T and longitudinal spatial scalar L
    G=sp.Matrix([
        [-D, 0],
        [ 1,-D],
        [ 0, 0],
        [ 0,-1],
    ])

    # y = R x = (Q,zeta)
    R=sp.Matrix([
        [1,D,0,-D**2],
        [0,0,1,0],
    ])
    checks={}
    checks['quotient_coordinates_are_gauge_invariant']=z(sp.simplify(R*G))
    checks['gauge_rank_is_two']=G.rank()==2
    checks['quotient_rank_is_two']=R.rank()==2

    H=sp.Matrix([[A,B],[B,C]])
    K=sp.simplify(R.T*H*R)
    checks['pulled_back_kernel_satisfies_Ward_identity']=z(sp.simplify(K*G))

    # Independent derivation: solve the Ward equations for a generic symmetric
    # 4x4 kernel and verify the solution space has dimension exactly three.
    q=sp.symbols('q0:10')
    Kgen=sp.Matrix([
        [q[0],q[1],q[2],q[3]],
        [q[1],q[4],q[5],q[6]],
        [q[2],q[5],q[7],q[8]],
        [q[3],q[6],q[8],q[9]],
    ])
    eqvec=sp.Matrix(Kgen*G)
    coeff=sp.zeros(8,10)
    for r,e in enumerate(eqvec):
        for c,qq in enumerate(q):
            coeff[r,c]=sp.diff(e,qq)
    ward_rank=coeff.rank()
    ward_dim=10-ward_rank
    checks['generic_symmetric_Ward_solution_dimension_is_three']=ward_dim==3

    # Show exact equivalence to the pullback parameterization by solving Ward.
    sol=sp.solve(list(eqvec),list(q),dict=True)
    checks['generic_Ward_system_has_one_parametric_solution_family']=len(sol)==1
    if sol:
        Ks=sp.simplify(Kgen.subs(sol[0]))
        # Identify A=q9/D^4, B=-q8/D^2, C=q7 in the generic solution.
        mapABC={A:q[9]/D**4, B:-q[8]/D**2, C:q[7]}
        Kpull_generic=sp.simplify(K.subs(mapABC))
        checks['generic_solution_equals_Q_zeta_pullback']=z(sp.simplify(Ks-Kpull_generic))
    else:
        Ks=sp.zeros(4)
        checks['generic_solution_equals_Q_zeta_pullback']=False

    # Negative control: an arbitrary lapse mass/stiffness violates Ward.
    eps=sp.symbols('epsilon', nonzero=True)
    Kbad=sp.simplify(K+sp.diag(eps,0,0,0))
    bad_res=sp.simplify(Kbad*G)
    checks['arbitrary_lapse_stiffness_negative_control_fails_Ward']=not z(bad_res)

    # Gauge-compatible source vectors must also be pullbacks from quotient
    # sources, J=R^T j, so G^T J=0.
    jQ,jZ=sp.symbols('jQ jZ')
    J=sp.simplify(R.T*sp.Matrix([jQ,jZ]))
    checks['quotient_source_has_zero_gauge_overlap']=z(sp.simplify(G.T*J))

    # In Newtonian gauge B=E=0 on flat background: Q=deltaN=Psi and
    # zeta=-Phi with our metric-sign convention.
    passed=bool(all(checks.values()))
    return {
        'schema':'BQG_SCALAR_ADM_WARD_BASIS_V1',
        'passed':passed,
        'science_status':'EXACT_FLAT_SCALAR_WARD_QUOTIENT_THREE_FUNCTIONS',
        'checks':checks,
        'field_basis':['deltaN','B','zeta','E'],
        'gauge_parameters':['T','L'],
        'gauge_generator':[[str(sp.simplify(G[i,j])) for j in range(G.cols)] for i in range(G.rows)],
        'quotient_coordinates':{
            'Q':'deltaN + D*B - D^2*E',
            'zeta':'zeta',
            'newtonian_gauge_flat_reference':'B=E=0 => Q=Psi, zeta=-Phi',
        },
        'quotient_map_R':[[str(sp.simplify(R[i,j])) for j in range(R.cols)] for i in range(R.rows)],
        'ward_parameter_count':ward_dim,
        'reduced_kernel':{
            'basis':['Q','zeta'],
            'H':[['A','B'],['B','C']],
            'quadratic_form':'A Q^2 + 2 B Q zeta + C zeta^2',
        },
        'full_Ward_kernel':[[str(sp.simplify(K[i,j])) for j in range(4)] for i in range(4)],
        'compatible_source_vector':[str(sp.simplify(x)) for x in J],
        'negative_control_Ward_residual':[[str(sp.simplify(bad_res[i,j])) for j in range(bad_res.cols)] for i in range(bad_res.rows)],
        'microscopic_consequence':'A theory-specific flat scalar metric Hessian needs only three Ward-compatible functions A(omega,k), B(omega,k), C(omega,k), not ten arbitrary symmetric ADM entries.',
        'claim_boundary':'Flat/local linear Ward quotient only. On FLRW, zeta mixes with time reparametrizations through the background expansion and the full background-dependent Bardeen/relational reduction must be derived. No BQG A,B,C values are supplied by this gate.'
    }


def main()->int:
    ap=argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--output',type=Path)
    a=ap.parse_args();out=run();txt=json.dumps(out,indent=2);print(txt)
    if a.output:
        a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(txt+'\n',encoding='utf-8')
    return 0 if out['passed'] else 1

if __name__=='__main__':
    raise SystemExit(main())
